[build]
  base = "login-ui"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  NEXT_TELEMETRY_DISABLED = "1"
  NEXT_PUBLIC_SUPABASE_URL = "https://placeholder.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "placeholder-key"
  NEXT_PUBLIC_API_BASE_URL = "https://auth.aryanstack.netlify.app"
  NEXT_PUBLIC_HYDRA_CLIENT_ID = "aais-login-ui"
  NEXT_PUBLIC_HYDRA_REDIRECT_URI = "https://login.aryanstack.netlify.app/callback"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/"
  to = "/login"
  status = 302

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
