[build]
  base = "admin-panel"
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NEXT_TELEMETRY_DISABLED = "1"
  NEXT_PUBLIC_SUPABASE_URL = "https://placeholder.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "placeholder-key"
  SUPABASE_SERVICE_ROLE_KEY = "placeholder-service-key"
  NEXT_PUBLIC_SSO_API_URL = "https://auth.aryanstack.netlify.app"
  NEXT_PUBLIC_ADMIN_API_URL = "https://auth.aryanstack.netlify.app/admin"
  NEXT_PUBLIC_HYDRA_PUBLIC_URL = "https://naughty-rubin-41sxbvuozm.projects.oryapis.com"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/"
  to = "/dashboard"
  status = 302

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
